'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const read = f => fs.readFileSync(path.join(root, f), 'utf8');
const values = new Map();
const storage = { getItem: k => values.get(k) ?? null, setItem: (k,v) => values.set(k,String(v)), removeItem: k => values.delete(k) };
const c = { console, localStorage: storage, document: {documentElement:{}}, getComputedStyle:()=>({getPropertyValue:()=>''}) };
vm.createContext(c); vm.runInContext(read('js/db.js'), c);
const db = c.DB;
const core = (name) => db.getExercises().find(e => e.part==='体幹' && e.name===name);
assert.equal(db.getExercises().filter(e=>e.part==='体幹').length,6);
assert.ok(db.getExercises().some(e=>e.part==='腹' && e.name==='プランク'));
const plank=db.addEntry('2026-09-23',core('プランク').id);
assert.equal(db.coreTotals(plank).sets,0,'empty sets are not completed training');
db.updateSet('2026-09-23',plank.id,0,'seconds',30);
db.updateSet('2026-09-23',plank.id,1,'seconds',30);
db.updateSet('2026-09-23',plank.id,2,'seconds',20);
assert.equal(db.coreTotals(plank).seconds,80);
assert.equal(db.coreTotals(plank).sets,3);
assert.equal(db.coreTotals(plank).longest,30);
db.addSet('2026-09-23',plank.id);
assert.equal(db.coreTotals(plank).sets,3,'adding a blank set does not inflate stats');
db.removeSet('2026-09-23',plank.id,3);
db.addSet('2026-09-23',plank.id,true);
assert.equal(db.coreTotals(plank).seconds,100,'explicit duplication copies values');
db.removeSet('2026-09-23',plank.id,3);
const side=db.addEntry('2026-09-23',core('サイドプランク').id);
assert.equal(side.coreSide,false,'new entries use a single value');
side.coreSide=true; // Legacy representation remains readable for migration and CSV compatibility.
db.updateSet('2026-09-23',side.id,0,'seconds',30);
assert.equal(db.coreTotals(side).partial,1);
db.updateSet('2026-09-23',side.id,0,'rightSeconds',25);
assert.equal(db.coreTotals(side).seconds,55);
assert.equal(db.coreTotals(side).sets,1,'left and right are one set');
assert.equal(db.coreTotals(side).partial,0);
const hold=db.addEntry('2026-09-23',core('バードドッグ').id);
hold.coreSide=true;
db.updateSet('2026-09-23',hold.id,0,'seconds',10);
assert.equal(db.coreTotals(hold).sets,0,'incomplete hold/repetition pair excluded');
assert.equal(db.coreTotals(hold).pending,true);
db.updateSet('2026-09-23',hold.id,0,'reps',5);
db.updateSet('2026-09-23',hold.id,0,'rightSeconds',8);
db.updateSet('2026-09-23',hold.id,0,'rightReps',4);
assert.equal(db.coreTotals(hold).seconds,82);
assert.equal(db.coreTotals(hold).reps,9);
const reps=db.addEntry('2026-09-23',core('デッドバグ').id);
reps.coreSide=true;
db.updateSet('2026-09-23',reps.id,0,'reps',10);
db.updateSet('2026-09-23',reps.id,0,'rightReps',12);
assert.equal(db.coreTotals(reps).reps,22);
assert.equal(db.coreTotals(reps).seconds,0);
for(const v of [Infinity,NaN,-1,1.5,86401]) assert.equal(db.coreValue(v),0);
db.updateSet('2026-09-23',plank.id,0,'w',100);
assert.equal(plank.sets[0].w,undefined,'core ignores strength fields');
db.updateExercise(core('プランク').id,{coreMode:'reps',coreSide:true});
assert.equal(plank.coreMode,'time','historical snapshots retain original mode');
assert.equal(db.prevRecord(plank.exId,'2026-09-24'),null,'incompatible previous values excluded');
assert.equal(db.addEntry('2026-09-24',plank.exId).coreMode,'reps');
assert.equal(db.bestRecords(plank.exId).length,0,'core excluded from volume rankings');

// Exercise and set snapshots must both survive CSV, even when the master mode changed.
Object.assign(c,{URL,Blob,INPUT_LIMITS:{exerciseName:100,equipment:100,exerciseNote:2000,dayMemo:5000,videoUrl:2048},
  limitedText:(v,max)=>String(v??'').slice(0,max),safeHttpsUrl:v=>v||'',
  parseDate:s=>new Date(s+'T00:00:00'),WD:['日','月','火','水','木','金','土'],
  isCore:e=>e.part==='体幹',isCardio:e=>e.part==='有酸素',zoneCsv:v=>v||'',zoneOf:s=>s.z||'',zoneFromCsv:v=>v||'',CARDIO_PART:'有酸素'});
const app=read('js/app.js');
vm.runInContext(app.slice(app.indexOf('  /* ================== CSVエクスポート用の行データ'),app.indexOf('  /* ================== RM計算機')),c);
const rows=[Array.from(c.ROW_HEAD),...c.rowsForDate('2026-09-23'),...c.rowsForDate('2026-09-24'),...c.rowsForExerciseMaster()];
for(const r of rows)assert.equal(r.length,27);
const parsed=c.buildImportData(rows);
const backup=db.exportStateJSON();
db.wipe();db.applyImport(parsed.dateOrder,parsed.byDate);db.importExercises(parsed.exercises,true);
const restored=db.getWorkout('2026-09-23').entries;
const restoredPlank=restored.find(e=>e.name==='プランク');
assert.equal(restoredPlank.coreMode,'time');assert.equal(db.coreTotals(restoredPlank).seconds,80);
assert.equal(db.getExercise(restoredPlank.exId).coreMode,'reps');
assert.equal(db.coreTotals(restored.find(e=>e.name==='バードドッグ')).seconds,82);
assert.equal(db.coreTotals(restored.find(e=>e.name==='デッドバグ')).reps,22);
assert.ok(c.rowsForDate('2026-09-23').every(r=>r[6]==='' && r[7]==='' && r[8]===''),'no fake weight or volume in CSV');
const bad=Array.from(rows[1]);bad[21]='broken';assert.throws(()=>c.buildImportData([rows[0],bad]),/体幹/);
const decimal=Array.from(rows[1]);decimal[23]='1.5';assert.throws(()=>c.buildImportData([rows[0],decimal]),/整数/);
assert.ok(db.restoreStateJSON(backup));assert.equal(db.coreTotals(db.getWorkout('2026-09-23').entries[0]).seconds,80);
const snapshot=storage.getItem(db.PRE_CORE_KEY);vm.runInContext(read('js/db.js'),c);assert.equal(storage.getItem(db.PRE_CORE_KEY),snapshot,'relaunch cannot overwrite migration backup');
assert.equal(c.DB.getExercises().filter(e=>e.part==='体幹').length,6,'migration is idempotent');
const charts=read('js/charts.js').replace('return { init: init };','return { init: init, collect: collectExerciseSessions, volume: volumeByPartBuckets };');
vm.runInContext(charts,c);const series=c.Charts.collect(plank.exId);assert.equal(series[0].seconds,80);assert.equal(series[0].core,true);assert.equal(c.Charts.volume('day').maxTotal,0);
// Backup write failure must not destroy the previous DB.
const legacy={version:2,exercises:[{id:'a',name:'旧プランク',part:'腹',equip:'自重'}],workouts:{'2026-09-20':{entries:[{id:'e',exId:'a',part:'腹',sets:[{w:0,r:10}]}]}},dirtyDates:{},dirtyExercises:false,deletedExercises:[]};
const raw=JSON.stringify(legacy);let saved=raw;
const fail={...c,localStorage:{getItem:k=>k==='kintore_v1'?raw:null,setItem:(k,v)=>{if(k!=='kintore_v1')throw Error('quota');saved=v}}};
vm.createContext(fail);assert.throws(()=>vm.runInContext(read('js/db.js'),fail),/quota/);assert.equal(saved,raw);
console.log('Core check passed: 3 modes / bilateral and partial sets / validation / snapshots / CSV and JSON round-trip / chart and volume isolation / migration and backup failure');
