'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../js/db.js'),'utf8');
const old={version:2,coreSchema:1,exercises:[{id:'core',name:'保持運動',part:'体幹',equip:'チューブ',coreMode:'hold',coreSide:true}],workouts:{'2026-09-23':{entries:[{id:'entry',exId:'core',name:'保持運動',part:'体幹',equip:'チューブ',coreMode:'hold',coreSide:true,sets:[{seconds:10,reps:5,rightSeconds:8,rightReps:4},{seconds:'',reps:'',rightSeconds:20,rightReps:2},{seconds:5,reps:'',rightSeconds:'',rightReps:''}]}]}},dirtyDates:{},dirtyExercises:false,deletedExercises:[]};
const values=new Map([['kintore_v1',JSON.stringify(old)]]);
const c={console,localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},document:{documentElement:{}},getComputedStyle:()=>({getPropertyValue:()=>''})};vm.createContext(c);vm.runInContext(source,c);
const d=c.DB,entry=d.getWorkout('2026-09-23').entries[0];
assert.equal(entry.coreSide,false);assert.equal(entry.sets.length,4);
assert.deepEqual(JSON.parse(JSON.stringify(entry.legacyCoreSets)),old.workouts['2026-09-23'].entries[0].sets);
assert.equal(entry.sets[1].seconds,8);assert.equal(entry.sets[1].reps,4);
assert.equal(entry.sets[2].seconds,20);assert.equal(entry.sets[3].seconds,5);
assert.equal(d.coreTotals(entry).seconds,122);assert.equal(d.coreTotals(entry).reps,11);
assert.equal(d.coreTotals(entry).sets,3);assert.equal(d.coreTotals(entry).pending,true);
assert.deepEqual(JSON.parse(values.get('kintore_v1_pre_input_b_20260923')),old);
assert.equal(d.getExercise('core').coreSide,false);assert.equal(d.getExercise('core').equip,'');assert.equal(d.getExercise('core').legacyEquip,'チューブ');
assert(!d.EQUIPS.includes('チューブ'));assert(!d.EQUIPS.includes('バランスボール'));
const after=d.exportStateJSON();vm.runInContext(source,c);assert.equal(c.DB.exportStateJSON(),after,'migration does not duplicate rows on relaunch');
const snapshot=values.get('kintore_v1_pre_input_b_20260923');c.DB.restoreStateJSON(JSON.stringify(old));assert.equal(c.DB.coreTotals(c.DB.getWorkout('2026-09-23').entries[0]).seconds,122);assert.equal(values.get('kintore_v1_pre_input_b_20260923'),snapshot);
console.log('Input B check passed: legacy bilateral values and original JSON preserved, independent rows, missing values, retired equipment, idempotent migration and JSON restore.');
